version: "3.8"

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: github_analysis_app
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./backend/api:/var/www/html
    networks:
      - github_analysis_network
    depends_on:
      - db

  web:
    image: nginx:1.21
    container_name: github_analysis_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend/api:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - github_analysis_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    platform: linux/arm64/v8
    container_name: github_analysis_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: github_analysis
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    ports:
      - "33060:3306"
    volumes:
      - github_analysis_db_data:/var/lib/mysql
    networks:
      - github_analysis_network

  frontend:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: github_analysis_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    networks:
      - github_analysis_network
    command: sh -c "npm install && npm run dev -- --host"

networks:
  github_analysis_network:
    driver: bridge

volumes:
  github_analysis_db_data:
